### ISSUE TITLE
Incorrect namespace when composer is not in the root directory

### ISSUE THREAD

**Issue by andythorne** [jaguadoromero/vscode-php-create-class#22]
I have a monorepo, where all the php files live under `php/`, with the composer file residing at `php/composer.json`. 

If `php/src` was mapped to `App\`, then when generating a new class in `php/src/Libs`, I would expect the namespace to be `App\Libs`, but the namespace is `php\App\Libs`.

This is only happening after 0.15.0.

**Comment by jaguadoromero** [comment]
@andythorne  If I understood correctly, you have a folder that is the one you have opened in vscode, which contains another `php` folder and that is where the `composer.json` file is located.

Trying to reproduce your issue, I have these folder structure:
```shell
projects
└── php
    ├── composer.json
    └── src
        └── Libs
``` 

And the `autoload` part of `composer.json` can be something like this:
```json
{
    "autoload": {
        "psr-4": {
            "App\\": "php/src/"
        }
    },
}
```
Note the last slash after `php/src`, it should be optional, but I recognize that there's currently a bug I'm fixing that makes that last slash necessary at the moment of writing this.
But this is not related by your issue.

Also note that adding this `php/src` folder in this `composer.json` I think is invalid.
The `autoload` spec says that folders should be relative to the location of `composer.json`, so adding the `php`part is invalid since `composer.json` is already in that folder.

Anyway, I have tested and the extension has correctly generated the namespace as `App\Libs`.

In next gif you can see the test that I have done:
![php-create-class](https://github.com/jaguadoromero/vscode-php-create-class/assets/1807023/0628b2c1-414d-4721-8df0-0e8ea904af39)

**Comment by andythorne** [comment]
Hey, this is my setup that will recreate the issue:

directory structure:
```
projects
└── php
    ├── composer.json
    └── src
        └── Libs
```

`php/composer.json`:
```
{
    "name": "some/test",
    "type": "library",
    "version": "1.0.0",
    "autoload": {
      "psr-4": {
        "SomeThing\\": "src/"
      }
    }
  }

```

Steps to recreate:
1. Create a new class called `Test` in `php/src/Libs`
2. Namespace will be `namespace php\Jefb\Framework\Libs;`, not `Jefb\Framework\Libs`.
```php
<?php

declare(strict_types=1);

namespace php\Jefb\Framework\Libs;

final class Test
{

}
```

**Comment by andythorne** [comment]
Hey, this is my setup that will recreate the issue:

directory structure:
```
projects
└── php
    ├── composer.json
    └── src
        └── Libs
```

`php/composer.json`:
```
{
    "name": "some/test",
    "type": "library",
    "version": "1.0.0",
    "autoload": {
      "psr-4": {
        "SomeThing\\": "src/"
      }
    }
  }

```

Steps to recreate:
1. Create a new class called `Test` in `php/src/Libs`
2. Namespace will be `php\SomeThing\Libs`, not `SomeThing\Libs`.
```php
<?php

declare(strict_types=1);

namespace php\SomeThing\Libs;

final class Test
{

}
```

**Comment by jaguadoromero** [comment]
@andythorne I just published an update with a fix for this problem.

**Comment by andythorne** [comment]
Thank you! 🙏

**Comment by lexman1958** [comment]
@jaguadoromero 

I am not sure you fixed the problem. Perhaps the fix has created a bigger problem. Refer to Issue #23
