### ISSUE TITLE
[Feature Request]  Setting to define the composer.json location

### ISSUE THREAD

**Issue by sofyansitorus** [jaguadoromero/vscode-php-create-class#24]
Hello,

Could you add a new setting to set the location of the composer.json file explicitly?

Thanks

**Comment by jaguadoromero** [comment]
I think vscode doesn't allow extension configuration at the workspace level, unless you manually create the `.vscode/settings.json` file.

Anyway, I don't understand in which case you would need to manually define the location of the `composer.json` file, since the extension itself finds the closest `composer.json` starting from the folder in which you want to create the class, and iterating back one level above until it finds `composer.json`.

**Comment by YanKolosovsky** [comment]
Folder composer: `\include\libs\composer\composer.json`
Folder application with structure: `\application`

in `composer.json`
```
"psr-4": {
      "Application\\": "../../../application"
}
```

I have problem on New Class in application folder: The composer.json file could not be found

What need write in `settings.json` ?
Thanks )

**Comment by jaguadoromero** [comment]
@YanKolosovsky I just published an update with this feature. 
Now, in the extension settings, there is a new option **Composer File path** where you can specify the relative path to the `composer.json` file. 
This setting can be setted at workspace level (useful in your case) and at User/global level (is not really useful).
In your case, the path would be `include/libs/composer/composer.json`. 
Note that the slashes are "unix style" but not like in Windows, for compatibility.
